// MDIFastTemplates_1_1.cpp generated by mFAST from FAST Template. 
// Do not modify this file directly. Any modifications 
// will be lost the next time this file is generated.

#include "MDIFastTemplates_1_1.h"

using namespace mfast;

namespace MDIFastTemplates_1_1
{
const MDPacketHeader::instruction_type*
MDPacketHeader::instruction()
{
  const static MDPacketHeader::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static uint32_field_instruction
MDPacketHeader__SenderCompID_instruction(
  operator_none,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static byte_vector_field_instruction
MDPacketHeader__PacketSeqNum_instruction(
  operator_none,
  presence_mandatory,
  0, // id
  "PacketSeqNum", // name
  "", // ns
  nullptr,  // opContext
  byte_vector_value_storage(), // initial value
  0, // length id
  "", // length name
  "", // length ns
  mfast::instruction_tag(0)); // tag

const static byte_vector_field_instruction
MDPacketHeader__SendingTime_instruction(
  operator_none,
  presence_mandatory,
  0, // id
  "SendingTime", // name
  "", // ns
  nullptr,  // opContext
  byte_vector_value_storage(), // initial value
  0, // length id
  "", // length name
  "", // length ns
  mfast::instruction_tag(0)); // tag

const static field_instruction* MDPacketHeader__subinstructions[] = {
  &MDPacketHeader__SenderCompID_instruction,
  &MDPacketHeader__PacketSeqNum_instruction,
  &MDPacketHeader__SendingTime_instruction,
};

  const static MDPacketHeader::instruction_type the_instruction(
    65, // id
    "MDPacketHeader", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    MDPacketHeader__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const ProductStateChange::instruction_type*
ProductStateChange::instruction()
{
  const static ProductStateChange::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
ProductStateChange__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("h",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__TradingSessionID_instruction(
  operator_default,
  presence_mandatory,
  336, // id
  "TradingSessionID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__TradingSessionSubID_instruction(
  operator_none,
  presence_mandatory,
  625, // id
  "TradingSessionSubID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__TradSesStatus_instruction(
  operator_none,
  presence_mandatory,
  340, // id
  "TradSesStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__MarketCondition_instruction(
  operator_default,
  presence_optional,
  2705, // id
  "MarketCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__FastMarketIndicator_instruction(
  operator_default,
  presence_mandatory,
  2447, // id
  "FastMarketIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
ProductStateChange__TransactTime_instruction(
  operator_none,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__TESTradSesStatus_instruction(
  operator_none,
  presence_optional,
  25044, // id
  "TESTradSesStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* ProductStateChange__subinstructions[] = {
  &ProductStateChange__MsgType_instruction,
  &ProductStateChange__MsgSeqNum_instruction,
  &ProductStateChange__SenderCompID_instruction,
  &ProductStateChange__MarketSegmentID_instruction,
  &ProductStateChange__TradingSessionID_instruction,
  &ProductStateChange__TradingSessionSubID_instruction,
  &ProductStateChange__TradSesStatus_instruction,
  &ProductStateChange__MarketCondition_instruction,
  &ProductStateChange__FastMarketIndicator_instruction,
  &ProductStateChange__TransactTime_instruction,
  &ProductStateChange__TESTradSesStatus_instruction,
};

  const static ProductStateChange::instruction_type the_instruction(
    108, // id
    "ProductStateChange", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    ProductStateChange__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const MassInstrumentStateChange::instruction_type*
MassInstrumentStateChange::instruction()
{
  const static MassInstrumentStateChange::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
MassInstrumentStateChange__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("CO",2), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__InstrumentScopeProductComplex_instruction(
  operator_copy,
  presence_mandatory,
  1544, // id
  "InstrumentScopeProductComplex", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecurityMassStatus_instruction(
  operator_default,
  presence_mandatory,
  30965, // id
  "SecurityMassStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecurityMassTradingStatus_instruction(
  operator_copy,
  presence_optional,
  1679, // id
  "SecurityMassTradingStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__MassMarketCondition_instruction(
  operator_default,
  presence_mandatory,
  28894, // id
  "MassMarketCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__FastMarketIndicator_instruction(
  operator_default,
  presence_mandatory,
  2447, // id
  "FastMarketIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecurityMassTradingEvent_instruction(
  operator_default,
  presence_optional,
  1680, // id
  "SecurityMassTradingEvent", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__MassSoldOutIndicator_instruction(
  operator_default,
  presence_optional,
  35155, // id
  "MassSoldOutIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
MassInstrumentStateChange__TransactTime_instruction(
  operator_delta,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__TESSecurityMassStatus_instruction(
  operator_default,
  presence_optional,
  35045, // id
  "TESSecurityMassStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecMassStatGrp_length_instruction(
  operator_default,
  presence_mandatory,
  146, // id
  "NoRelatedSym", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U)); // initial_value

const static int64_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecurityID_instruction(
  operator_none,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecurityStatus_instruction(
  operator_default,
  presence_mandatory,
  965, // id
  "SecurityStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecurityTradingStatus_instruction(
  operator_copy,
  presence_optional,
  326, // id
  "SecurityTradingStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__MarketCondition_instruction(
  operator_default,
  presence_mandatory,
  2705, // id
  "MarketCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecurityTradingEvent_instruction(
  operator_default,
  presence_optional,
  1174, // id
  "SecurityTradingEvent", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SoldOutIndicator_instruction(
  operator_default,
  presence_optional,
  25155, // id
  "SoldOutIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__TESSecurityStatus_instruction(
  operator_copy,
  presence_optional,
  25045, // id
  "TESSecurityStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* MassInstrumentStateChange__SecMassStatGrp_element__subinstructions[] = {
  &MassInstrumentStateChange__SecMassStatGrp_element__SecurityID_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_element__SecurityIDSource_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_element__SecurityStatus_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_element__SecurityTradingStatus_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_element__MarketCondition_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_element__SecurityTradingEvent_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_element__SoldOutIndicator_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_element__TESSecurityStatus_instruction,
};

const static MassInstrumentStateChange_cref::SecMassStatGrp_cref::instruction_type
MassInstrumentStateChange__SecMassStatGrp_instruction(
  presence_mandatory,
  0, // id
  "SecMassStatGrp", // name
  "", // ns
  "", // dictionary
  MassInstrumentStateChange__SecMassStatGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &MassInstrumentStateChange__SecMassStatGrp_element__SecMassStatGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static uint32_field_instruction
MassInstrumentStateChange__LastFragment_instruction(
  operator_default,
  presence_mandatory,
  893, // id
  "LastFragment", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* MassInstrumentStateChange__subinstructions[] = {
  &MassInstrumentStateChange__MsgType_instruction,
  &MassInstrumentStateChange__MsgSeqNum_instruction,
  &MassInstrumentStateChange__SenderCompID_instruction,
  &MassInstrumentStateChange__MarketSegmentID_instruction,
  &MassInstrumentStateChange__InstrumentScopeProductComplex_instruction,
  &MassInstrumentStateChange__SecurityMassStatus_instruction,
  &MassInstrumentStateChange__SecurityMassTradingStatus_instruction,
  &MassInstrumentStateChange__MassMarketCondition_instruction,
  &MassInstrumentStateChange__FastMarketIndicator_instruction,
  &MassInstrumentStateChange__SecurityMassTradingEvent_instruction,
  &MassInstrumentStateChange__MassSoldOutIndicator_instruction,
  &MassInstrumentStateChange__TransactTime_instruction,
  &MassInstrumentStateChange__TESSecurityMassStatus_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_instruction,
  &MassInstrumentStateChange__LastFragment_instruction,
};

  const static MassInstrumentStateChange::instruction_type the_instruction(
    104, // id
    "MassInstrumentStateChange", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    MassInstrumentStateChange__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const InstrumentStateChange::instruction_type*
InstrumentStateChange::instruction()
{
  const static InstrumentStateChange::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
InstrumentStateChange__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("f",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
InstrumentStateChange__SecurityID_instruction(
  operator_none,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
InstrumentStateChange__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__SecurityStatus_instruction(
  operator_default,
  presence_mandatory,
  965, // id
  "SecurityStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__SecurityTradingStatus_instruction(
  operator_copy,
  presence_optional,
  326, // id
  "SecurityTradingStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__MarketCondition_instruction(
  operator_default,
  presence_mandatory,
  2705, // id
  "MarketCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__FastMarketIndicator_instruction(
  operator_default,
  presence_mandatory,
  2447, // id
  "FastMarketIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__SecurityTradingEvent_instruction(
  operator_copy,
  presence_optional,
  1174, // id
  "SecurityTradingEvent", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__SoldOutIndicator_instruction(
  operator_copy,
  presence_optional,
  25155, // id
  "SoldOutIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
InstrumentStateChange__TransactTime_instruction(
  operator_delta,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__TESSecurityStatus_instruction(
  operator_default,
  presence_optional,
  25045, // id
  "TESSecurityStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* InstrumentStateChange__subinstructions[] = {
  &InstrumentStateChange__MsgType_instruction,
  &InstrumentStateChange__MsgSeqNum_instruction,
  &InstrumentStateChange__SenderCompID_instruction,
  &InstrumentStateChange__MarketSegmentID_instruction,
  &InstrumentStateChange__SecurityID_instruction,
  &InstrumentStateChange__SecurityIDSource_instruction,
  &InstrumentStateChange__SecurityStatus_instruction,
  &InstrumentStateChange__SecurityTradingStatus_instruction,
  &InstrumentStateChange__MarketCondition_instruction,
  &InstrumentStateChange__FastMarketIndicator_instruction,
  &InstrumentStateChange__SecurityTradingEvent_instruction,
  &InstrumentStateChange__SoldOutIndicator_instruction,
  &InstrumentStateChange__TransactTime_instruction,
  &InstrumentStateChange__TESSecurityStatus_instruction,
};

  const static InstrumentStateChange::instruction_type the_instruction(
    103, // id
    "InstrumentStateChange", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    InstrumentStateChange__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const DepthIncremental::instruction_type*
DepthIncremental::instruction()
{
  const static DepthIncremental::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
DepthIncremental__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("X",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
DepthIncremental__MDIncGrp_element__MDIncGrp_length_instruction(
  operator_none,
  presence_mandatory,
  268, // id
  "NoMDEntries", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>()); // initial_value

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__MDOriginType_instruction(
  operator_default,
  presence_mandatory,
  1024, // id
  "MDOriginType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__MDUpdateAction_instruction(
  operator_copy,
  presence_mandatory,
  279, // id
  "MDUpdateAction", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__MDEntryType_instruction(
  operator_copy,
  presence_mandatory,
  269, // id
  "MDEntryType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthIncremental__MDIncGrp_element__SecurityID_instruction(
  operator_copy,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
DepthIncremental__MDIncGrp_element__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__MDEntryPx_instruction(
  operator_delta,
  presence_optional,
  270, // id
  "MDEntryPx", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__MDEntrySize_instruction(
  operator_delta,
  presence_optional,
  271, // id
  "MDEntrySize", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__NumberOfOrders_instruction(
  operator_delta,
  presence_optional,
  346, // id
  "NumberOfOrders", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__MDPriceLevel_instruction(
  operator_none,
  presence_optional,
  1023, // id
  "MDPriceLevel", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthIncremental__MDIncGrp_element__MDEntryTime_instruction(
  operator_copy,
  presence_optional,
  273, // id
  "MDEntryTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__PotentialSecurityTradingEvent_instruction(
  operator_none,
  presence_optional,
  28872, // id
  "PotentialSecurityTradingEvent", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__QuoteCondition_instruction(
  operator_none,
  presence_optional,
  276, // id
  "QuoteCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__TotalBuyQuantity_instruction(
  operator_delta,
  presence_optional,
  134, // id
  "TotalBuyQuantity", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__TotalSellQuantity_instruction(
  operator_delta,
  presence_optional,
  135, // id
  "TotalSellQuantity", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__TrdType_instruction(
  operator_none,
  presence_optional,
  828, // id
  "TrdType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__AlgorithmicTradeIndicator_instruction(
  operator_default,
  presence_optional,
  2667, // id
  "AlgorithmicTradeIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint64_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__TradeCondition_instruction(
  operator_default,
  presence_optional,
  277, // id
  "TradeCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint64_t>(1ULL), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__MultiLegReportingType_instruction(
  operator_default,
  presence_optional,
  442, // id
  "MultiLegReportingType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__MultiLegPriceModel_instruction(
  operator_default,
  presence_optional,
  28750, // id
  "MultiLegPriceModel", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__AggressorTime_instruction(
  operator_none,
  presence_optional,
  2445, // id
  "AggressorTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__RequestTime_instruction(
  operator_none,
  presence_optional,
  5979, // id
  "RequestTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__AggressorSide_instruction(
  operator_none,
  presence_optional,
  2446, // id
  "AggressorSide", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__NumberOfBuyOrders_instruction(
  operator_none,
  presence_optional,
  2449, // id
  "NumberOfBuyOrders", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__NumberOfSellOrders_instruction(
  operator_none,
  presence_optional,
  2450, // id
  "NumberOfSellOrders", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__TotalNumOfTrades_instruction(
  operator_none,
  presence_optional,
  6139, // id
  "TotalNumOfTrades", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__RestingCxlQty_instruction(
  operator_none,
  presence_optional,
  28869, // id
  "RestingCxlQty", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__MDEntryID_instruction(
  operator_delta,
  presence_optional,
  278, // id
  "MDEntryID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__TotalTradedValue_instruction(
  operator_delta,
  presence_optional,
  381, // id
  "TotalTradedValue", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__AverageTradedPrice_instruction(
  operator_delta,
  presence_optional,
  426, // id
  "AverageTradedPrice", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__NonDisclosedTradeVolume_instruction(
  operator_none,
  presence_optional,
  28873, // id
  "NonDisclosedTradeVolume", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* DepthIncremental__MDIncGrp_element__TradeEntryGrp__subinstructions[] = {
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__TrdType_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__AlgorithmicTradeIndicator_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__TradeCondition_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__MultiLegReportingType_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__MultiLegPriceModel_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__AggressorTime_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__RequestTime_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__AggressorSide_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__NumberOfBuyOrders_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__NumberOfSellOrders_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__TotalNumOfTrades_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__RestingCxlQty_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__MDEntryID_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__TotalTradedValue_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__AverageTradedPrice_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__NonDisclosedTradeVolume_instruction,
};

const static DepthIncremental_cref::MDIncGrp_element_cref::TradeEntryGrp_cref::instruction_type
DepthIncremental__MDIncGrp_element__TradeEntryGrp_instruction(
  presence_optional,
  0, // id
  "TradeEntryGrp", // name
  "", // ns
  "", // dictionary
  DepthIncremental__MDIncGrp_element__TradeEntryGrp__subinstructions,
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag

const static field_instruction* DepthIncremental__MDIncGrp_element__subinstructions[] = {
  &DepthIncremental__MDIncGrp_element__MDOriginType_instruction,
  &DepthIncremental__MDIncGrp_element__MDUpdateAction_instruction,
  &DepthIncremental__MDIncGrp_element__MDEntryType_instruction,
  &DepthIncremental__MDIncGrp_element__SecurityID_instruction,
  &DepthIncremental__MDIncGrp_element__SecurityIDSource_instruction,
  &DepthIncremental__MDIncGrp_element__MDEntryPx_instruction,
  &DepthIncremental__MDIncGrp_element__MDEntrySize_instruction,
  &DepthIncremental__MDIncGrp_element__NumberOfOrders_instruction,
  &DepthIncremental__MDIncGrp_element__MDPriceLevel_instruction,
  &DepthIncremental__MDIncGrp_element__MDEntryTime_instruction,
  &DepthIncremental__MDIncGrp_element__PotentialSecurityTradingEvent_instruction,
  &DepthIncremental__MDIncGrp_element__QuoteCondition_instruction,
  &DepthIncremental__MDIncGrp_element__TotalBuyQuantity_instruction,
  &DepthIncremental__MDIncGrp_element__TotalSellQuantity_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp_instruction,
};

const static DepthIncremental_cref::MDIncGrp_cref::instruction_type
DepthIncremental__MDIncGrp_instruction(
  presence_mandatory,
  0, // id
  "MDIncGrp", // name
  "", // ns
  "", // dictionary
  DepthIncremental__MDIncGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &DepthIncremental__MDIncGrp_element__MDIncGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static field_instruction* DepthIncremental__subinstructions[] = {
  &DepthIncremental__MsgType_instruction,
  &DepthIncremental__MsgSeqNum_instruction,
  &DepthIncremental__SenderCompID_instruction,
  &DepthIncremental__MarketSegmentID_instruction,
  &DepthIncremental__MDIncGrp_instruction,
};

  const static DepthIncremental::instruction_type the_instruction(
    102, // id
    "DepthIncremental", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    DepthIncremental__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const ComplexInstrumentUpdate::instruction_type*
ComplexInstrumentUpdate::instruction()
{
  const static ComplexInstrumentUpdate::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
ComplexInstrumentUpdate__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("BP",2), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
ComplexInstrumentUpdate__SecurityUpdateAction_instruction(
  operator_constant,
  presence_mandatory,
  980, // id
  "SecurityUpdateAction", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("A",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
ComplexInstrumentUpdate__SecurityID_instruction(
  operator_none,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
ComplexInstrumentUpdate__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
ComplexInstrumentUpdate__SecurityDesc_instruction(
  operator_none,
  presence_mandatory,
  107, // id
  "SecurityDesc", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__SecurityType_instruction(
  operator_constant,
  presence_mandatory,
  167, // id
  "SecurityType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(2U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__SecuritySubType_instruction(
  operator_none,
  presence_optional,
  762, // id
  "SecuritySubType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__ProductComplex_instruction(
  operator_copy,
  presence_mandatory,
  1227, // id
  "ProductComplex", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__LegRatioMultiplier_instruction(
  operator_default,
  presence_optional,
  28900, // id
  "LegRatioMultiplier", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__InstrmtLegGrp_length_instruction(
  operator_none,
  presence_mandatory,
  555, // id
  "NoLegs", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>()); // initial_value

const static uint32_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSymbol_instruction(
  operator_copy,
  presence_mandatory,
  600, // id
  "LegSymbol", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSecurityID_instruction(
  operator_none,
  presence_mandatory,
  602, // id
  "LegSecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  603, // id
  "LegSecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSecurityType_instruction(
  operator_default,
  presence_mandatory,
  609, // id
  "LegSecurityType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegRatioQty_instruction(
  operator_none,
  presence_mandatory,
  623, // id
  "LegRatioQty", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSide_instruction(
  operator_copy,
  presence_mandatory,
  624, // id
  "LegSide", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegPrice_instruction(
  operator_none,
  presence_optional,
  566, // id
  "LegPrice", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* ComplexInstrumentUpdate__InstrmtLegGrp_element__subinstructions[] = {
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSymbol_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSecurityID_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSecurityIDSource_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSecurityType_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegRatioQty_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSide_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegPrice_instruction,
};

const static ComplexInstrumentUpdate_cref::InstrmtLegGrp_cref::instruction_type
ComplexInstrumentUpdate__InstrmtLegGrp_instruction(
  presence_mandatory,
  0, // id
  "InstrmtLegGrp", // name
  "", // ns
  "", // dictionary
  ComplexInstrumentUpdate__InstrmtLegGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__InstrmtLegGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

static uint32_field_instruction
ComplexInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentGrp_length_instruction(
  operator_constant,
  presence_mandatory,
  1310, // id
  "NoMarketSegments", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U)); // initial_value

const static uint32_field_instruction
ComplexInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__MarketSegmentGrp_element__ImpliedMarketIndicator_instruction(
  operator_none,
  presence_mandatory,
  1144, // id
  "ImpliedMarketIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* ComplexInstrumentUpdate__MarketSegmentGrp_element__subinstructions[] = {
  &ComplexInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentID_instruction,
  &ComplexInstrumentUpdate__MarketSegmentGrp_element__ImpliedMarketIndicator_instruction,
};

const static ComplexInstrumentUpdate_cref::MarketSegmentGrp_cref::instruction_type
ComplexInstrumentUpdate__MarketSegmentGrp_instruction(
  presence_mandatory,
  0, // id
  "MarketSegmentGrp", // name
  "", // ns
  "", // dictionary
  ComplexInstrumentUpdate__MarketSegmentGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &ComplexInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static int64_field_instruction
ComplexInstrumentUpdate__TransactTime_instruction(
  operator_none,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* ComplexInstrumentUpdate__subinstructions[] = {
  &ComplexInstrumentUpdate__MsgType_instruction,
  &ComplexInstrumentUpdate__MsgSeqNum_instruction,
  &ComplexInstrumentUpdate__SenderCompID_instruction,
  &ComplexInstrumentUpdate__SecurityUpdateAction_instruction,
  &ComplexInstrumentUpdate__SecurityID_instruction,
  &ComplexInstrumentUpdate__SecurityIDSource_instruction,
  &ComplexInstrumentUpdate__SecurityDesc_instruction,
  &ComplexInstrumentUpdate__SecurityType_instruction,
  &ComplexInstrumentUpdate__SecuritySubType_instruction,
  &ComplexInstrumentUpdate__ProductComplex_instruction,
  &ComplexInstrumentUpdate__LegRatioMultiplier_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_instruction,
  &ComplexInstrumentUpdate__MarketSegmentGrp_instruction,
  &ComplexInstrumentUpdate__TransactTime_instruction,
};

  const static ComplexInstrumentUpdate::instruction_type the_instruction(
    105, // id
    "ComplexInstrumentUpdate", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    ComplexInstrumentUpdate__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const QuoteRequest::instruction_type*
QuoteRequest::instruction()
{
  const static QuoteRequest::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
QuoteRequest__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("R",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
QuoteRequest__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
QuoteRequest__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
QuoteRequest__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
QuoteRequest__QuotReqGrp_element__QuotReqGrp_length_instruction(
  operator_constant,
  presence_mandatory,
  146, // id
  "NoRelatedSym", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U)); // initial_value

const static int64_field_instruction
QuoteRequest__QuotReqGrp_element__SecurityID_instruction(
  operator_copy,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
QuoteRequest__QuotReqGrp_element__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
QuoteRequest__QuotReqGrp_element__Side_instruction(
  operator_copy,
  presence_optional,
  54, // id
  "Side", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
QuoteRequest__QuotReqGrp_element__OrderQty_instruction(
  operator_delta,
  presence_optional,
  38, // id
  "OrderQty", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
QuoteRequest__QuotReqGrp_element__TransactTime_instruction(
  operator_copy,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* QuoteRequest__QuotReqGrp_element__subinstructions[] = {
  &QuoteRequest__QuotReqGrp_element__SecurityID_instruction,
  &QuoteRequest__QuotReqGrp_element__SecurityIDSource_instruction,
  &QuoteRequest__QuotReqGrp_element__Side_instruction,
  &QuoteRequest__QuotReqGrp_element__OrderQty_instruction,
  &QuoteRequest__QuotReqGrp_element__TransactTime_instruction,
};

const static QuoteRequest_cref::QuotReqGrp_cref::instruction_type
QuoteRequest__QuotReqGrp_instruction(
  presence_mandatory,
  0, // id
  "QuotReqGrp", // name
  "", // ns
  "", // dictionary
  QuoteRequest__QuotReqGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &QuoteRequest__QuotReqGrp_element__QuotReqGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static field_instruction* QuoteRequest__subinstructions[] = {
  &QuoteRequest__MsgType_instruction,
  &QuoteRequest__MsgSeqNum_instruction,
  &QuoteRequest__SenderCompID_instruction,
  &QuoteRequest__MarketSegmentID_instruction,
  &QuoteRequest__QuotReqGrp_instruction,
};

  const static QuoteRequest::instruction_type the_instruction(
    106, // id
    "QuoteRequest", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    QuoteRequest__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const CrossRequest::instruction_type*
CrossRequest::instruction()
{
  const static CrossRequest::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
CrossRequest__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("U16",3), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
CrossRequest__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
CrossRequest__SenderCompID_instruction(
  operator_none,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
CrossRequest__MarketSegmentID_instruction(
  operator_none,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
CrossRequest__SecurityID_instruction(
  operator_none,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
CrossRequest__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
CrossRequest__OrderQty_instruction(
  operator_none,
  presence_optional,
  38, // id
  "OrderQty", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
CrossRequest__CrossRequestType_instruction(
  operator_none,
  presence_mandatory,
  28771, // id
  "CrossRequestType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
CrossRequest__CrossRequestSideGrp_element__CrossRequestSideGrp_length_instruction(
  operator_constant,
  presence_optional,
  552, // id
  "NoCrossRequestSideGrp", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U)); // initial_value

const static uint32_field_instruction
CrossRequest__CrossRequestSideGrp_element__Side_instruction(
  operator_copy,
  presence_optional,
  54, // id
  "Side", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
CrossRequest__CrossRequestSideGrp_element__InputSource_instruction(
  operator_constant,
  presence_mandatory,
  979, // id
  "InputSource", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* CrossRequest__CrossRequestSideGrp_element__subinstructions[] = {
  &CrossRequest__CrossRequestSideGrp_element__Side_instruction,
  &CrossRequest__CrossRequestSideGrp_element__InputSource_instruction,
};

const static CrossRequest_cref::CrossRequestSideGrp_cref::instruction_type
CrossRequest__CrossRequestSideGrp_instruction(
  presence_optional,
  0, // id
  "CrossRequestSideGrp", // name
  "", // ns
  "", // dictionary
  CrossRequest__CrossRequestSideGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &CrossRequest__CrossRequestSideGrp_element__CrossRequestSideGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static decimal_field_instruction
CrossRequest__MDEntryPx_instruction(
  operator_none,
  presence_optional,
  270, // id
  "MDEntryPx", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
CrossRequest__TransactTime_instruction(
  operator_none,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* CrossRequest__subinstructions[] = {
  &CrossRequest__MsgType_instruction,
  &CrossRequest__MsgSeqNum_instruction,
  &CrossRequest__SenderCompID_instruction,
  &CrossRequest__MarketSegmentID_instruction,
  &CrossRequest__SecurityID_instruction,
  &CrossRequest__SecurityIDSource_instruction,
  &CrossRequest__OrderQty_instruction,
  &CrossRequest__CrossRequestType_instruction,
  &CrossRequest__CrossRequestSideGrp_instruction,
  &CrossRequest__MDEntryPx_instruction,
  &CrossRequest__TransactTime_instruction,
};

  const static CrossRequest::instruction_type the_instruction(
    107, // id
    "CrossRequest", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    CrossRequest__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const DepthSnapshot::instruction_type*
DepthSnapshot::instruction()
{
  const static DepthSnapshot::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
DepthSnapshot__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("W",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MsgSeqNum_instruction(
  operator_increment,
  presence_optional,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__LastMsgSeqNumProcessed_instruction(
  operator_increment,
  presence_optional,
  369, // id
  "LastMsgSeqNumProcessed", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__RefreshIndicator_instruction(
  operator_copy,
  presence_optional,
  1187, // id
  "RefreshIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthSnapshot__SecurityID_instruction(
  operator_delta,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
DepthSnapshot__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__ProductComplex_instruction(
  operator_copy,
  presence_mandatory,
  1227, // id
  "ProductComplex", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__SecurityStatus_instruction(
  operator_default,
  presence_mandatory,
  965, // id
  "SecurityStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__TESSecurityStatus_instruction(
  operator_none,
  presence_optional,
  25045, // id
  "TESSecurityStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthSnapshot__LastUpdateTime_instruction(
  operator_delta,
  presence_mandatory,
  779, // id
  "LastUpdateTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__TotalBuyQuantity_instruction(
  operator_delta,
  presence_optional,
  134, // id
  "TotalBuyQuantity", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__TotalSellQuantity_instruction(
  operator_delta,
  presence_optional,
  135, // id
  "TotalSellQuantity", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MDSshGrp_length_instruction(
  operator_default,
  presence_mandatory,
  268, // id
  "NoMDEntries", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U)); // initial_value

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MDOriginType_instruction(
  operator_default,
  presence_mandatory,
  1024, // id
  "MDOriginType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MDEntryType_instruction(
  operator_copy,
  presence_mandatory,
  269, // id
  "MDEntryType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MDBookType_instruction(
  operator_copy,
  presence_optional,
  1021, // id
  "MDBookType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MDSubBookType_instruction(
  operator_copy,
  presence_optional,
  1173, // id
  "MDSubBookType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__TrdType_instruction(
  operator_default,
  presence_optional,
  828, // id
  "TrdType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__TradingSessionID_instruction(
  operator_default,
  presence_optional,
  336, // id
  "TradingSessionID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__TradingSessionSubID_instruction(
  operator_default,
  presence_optional,
  625, // id
  "TradingSessionSubID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__TESTradSesStatus_instruction(
  operator_default,
  presence_optional,
  25044, // id
  "TESTradSesStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__SecurityTradingStatus_instruction(
  operator_default,
  presence_optional,
  326, // id
  "SecurityTradingStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MarketCondition_instruction(
  operator_default,
  presence_optional,
  2705, // id
  "MarketCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__FastMarketIndicator_instruction(
  operator_default,
  presence_optional,
  2447, // id
  "FastMarketIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__SecurityTradingEvent_instruction(
  operator_default,
  presence_optional,
  1174, // id
  "SecurityTradingEvent", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__PotentialSecurityTradingEvent_instruction(
  operator_default,
  presence_optional,
  28872, // id
  "PotentialSecurityTradingEvent", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__SoldOutIndicator_instruction(
  operator_default,
  presence_optional,
  25155, // id
  "SoldOutIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint64_field_instruction
DepthSnapshot__MDSshGrp_element__TradeCondition_instruction(
  operator_default,
  presence_optional,
  277, // id
  "TradeCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MultiLegReportingType_instruction(
  operator_default,
  presence_optional,
  442, // id
  "MultiLegReportingType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MultiLegPriceModel_instruction(
  operator_default,
  presence_optional,
  28750, // id
  "MultiLegPriceModel", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__QuoteCondition_instruction(
  operator_copy,
  presence_optional,
  276, // id
  "QuoteCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__MDSshGrp_element__MDEntryPx_instruction(
  operator_delta,
  presence_optional,
  270, // id
  "MDEntryPx", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__MDSshGrp_element__MDEntrySize_instruction(
  operator_delta,
  presence_optional,
  271, // id
  "MDEntrySize", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__NumberOfOrders_instruction(
  operator_delta,
  presence_optional,
  346, // id
  "NumberOfOrders", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MDPriceLevel_instruction(
  operator_increment,
  presence_optional,
  1023, // id
  "MDPriceLevel", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthSnapshot__MDSshGrp_element__MDEntryTime_instruction(
  operator_delta,
  presence_optional,
  273, // id
  "MDEntryTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__MDSshGrp_element__NonDisclosedTradeVolume_instruction(
  operator_default,
  presence_optional,
  28873, // id
  "NonDisclosedTradeVolume", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__MDSshGrp_element__TotalTradedValue_instruction(
  operator_delta,
  presence_optional,
  381, // id
  "TotalTradedValue", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__MDSshGrp_element__AverageTradedPrice_instruction(
  operator_delta,
  presence_optional,
  426, // id
  "AverageTradedPrice", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__TotalNumOfTrades_instruction(
  operator_default,
  presence_optional,
  6139, // id
  "TotalNumOfTrades", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* DepthSnapshot__MDSshGrp_element__subinstructions[] = {
  &DepthSnapshot__MDSshGrp_element__MDOriginType_instruction,
  &DepthSnapshot__MDSshGrp_element__MDEntryType_instruction,
  &DepthSnapshot__MDSshGrp_element__MDBookType_instruction,
  &DepthSnapshot__MDSshGrp_element__MDSubBookType_instruction,
  &DepthSnapshot__MDSshGrp_element__TrdType_instruction,
  &DepthSnapshot__MDSshGrp_element__TradingSessionID_instruction,
  &DepthSnapshot__MDSshGrp_element__TradingSessionSubID_instruction,
  &DepthSnapshot__MDSshGrp_element__TESTradSesStatus_instruction,
  &DepthSnapshot__MDSshGrp_element__SecurityTradingStatus_instruction,
  &DepthSnapshot__MDSshGrp_element__MarketCondition_instruction,
  &DepthSnapshot__MDSshGrp_element__FastMarketIndicator_instruction,
  &DepthSnapshot__MDSshGrp_element__SecurityTradingEvent_instruction,
  &DepthSnapshot__MDSshGrp_element__PotentialSecurityTradingEvent_instruction,
  &DepthSnapshot__MDSshGrp_element__SoldOutIndicator_instruction,
  &DepthSnapshot__MDSshGrp_element__TradeCondition_instruction,
  &DepthSnapshot__MDSshGrp_element__MultiLegReportingType_instruction,
  &DepthSnapshot__MDSshGrp_element__MultiLegPriceModel_instruction,
  &DepthSnapshot__MDSshGrp_element__QuoteCondition_instruction,
  &DepthSnapshot__MDSshGrp_element__MDEntryPx_instruction,
  &DepthSnapshot__MDSshGrp_element__MDEntrySize_instruction,
  &DepthSnapshot__MDSshGrp_element__NumberOfOrders_instruction,
  &DepthSnapshot__MDSshGrp_element__MDPriceLevel_instruction,
  &DepthSnapshot__MDSshGrp_element__MDEntryTime_instruction,
  &DepthSnapshot__MDSshGrp_element__NonDisclosedTradeVolume_instruction,
  &DepthSnapshot__MDSshGrp_element__TotalTradedValue_instruction,
  &DepthSnapshot__MDSshGrp_element__AverageTradedPrice_instruction,
  &DepthSnapshot__MDSshGrp_element__TotalNumOfTrades_instruction,
};

const static DepthSnapshot_cref::MDSshGrp_cref::instruction_type
DepthSnapshot__MDSshGrp_instruction(
  presence_mandatory,
  0, // id
  "MDSshGrp", // name
  "", // ns
  "", // dictionary
  DepthSnapshot__MDSshGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &DepthSnapshot__MDSshGrp_element__MDSshGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static field_instruction* DepthSnapshot__subinstructions[] = {
  &DepthSnapshot__MsgType_instruction,
  &DepthSnapshot__MsgSeqNum_instruction,
  &DepthSnapshot__SenderCompID_instruction,
  &DepthSnapshot__LastMsgSeqNumProcessed_instruction,
  &DepthSnapshot__RefreshIndicator_instruction,
  &DepthSnapshot__MarketSegmentID_instruction,
  &DepthSnapshot__SecurityID_instruction,
  &DepthSnapshot__SecurityIDSource_instruction,
  &DepthSnapshot__ProductComplex_instruction,
  &DepthSnapshot__SecurityStatus_instruction,
  &DepthSnapshot__TESSecurityStatus_instruction,
  &DepthSnapshot__LastUpdateTime_instruction,
  &DepthSnapshot__TotalBuyQuantity_instruction,
  &DepthSnapshot__TotalSellQuantity_instruction,
  &DepthSnapshot__MDSshGrp_instruction,
};

  const static DepthSnapshot::instruction_type the_instruction(
    101, // id
    "DepthSnapshot", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    DepthSnapshot__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const IndexStats::instruction_type*
IndexStats::instruction()
{
  const static IndexStats::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
IndexStats__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("I",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexStats__MsgSeqNum_instruction(
  operator_increment,
  presence_optional,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexStats__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexStats__MarketSegmentID_instruction(
  operator_copy,
  presence_optional,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
IndexStats__IndexHigh_instruction(
  operator_delta,
  presence_optional,
  40001, // id
  "IndexHigh", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
IndexStats__IndexLow_instruction(
  operator_delta,
  presence_optional,
  40002, // id
  "IndexLow", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
IndexStats__IndexOpen_instruction(
  operator_delta,
  presence_optional,
  40003, // id
  "IndexOpen", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
IndexStats__IndexClose_instruction(
  operator_delta,
  presence_optional,
  40004, // id
  "IndexClose", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
IndexStats__IndexValue_instruction(
  operator_delta,
  presence_optional,
  40005, // id
  "IndexValue", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
IndexStats__IndexLifeHigh_instruction(
  operator_delta,
  presence_optional,
  40006, // id
  "IndexLifeHigh", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
IndexStats__IndexLifeLow_instruction(
  operator_delta,
  presence_optional,
  40007, // id
  "IndexLifeLow", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
IndexStats__Index52WeekHigh_instruction(
  operator_delta,
  presence_optional,
  40008, // id
  "Index52WeekHigh", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
IndexStats__Index52WeekLow_instruction(
  operator_delta,
  presence_optional,
  40009, // id
  "Index52WeekLow", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexStats__CloseIndexFlag_instruction(
  operator_copy,
  presence_optional,
  400010, // id
  "CloseIndexFlag", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
IndexStats__TransactTime_instruction(
  operator_delta,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* IndexStats__subinstructions[] = {
  &IndexStats__MsgType_instruction,
  &IndexStats__MsgSeqNum_instruction,
  &IndexStats__SenderCompID_instruction,
  &IndexStats__MarketSegmentID_instruction,
  &IndexStats__IndexHigh_instruction,
  &IndexStats__IndexLow_instruction,
  &IndexStats__IndexOpen_instruction,
  &IndexStats__IndexClose_instruction,
  &IndexStats__IndexValue_instruction,
  &IndexStats__IndexLifeHigh_instruction,
  &IndexStats__IndexLifeLow_instruction,
  &IndexStats__Index52WeekHigh_instruction,
  &IndexStats__Index52WeekLow_instruction,
  &IndexStats__CloseIndexFlag_instruction,
  &IndexStats__TransactTime_instruction,
};

  const static IndexStats::instruction_type the_instruction(
    51, // id
    "IndexStats", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    IndexStats__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const TopOfBookImplied::instruction_type*
TopOfBookImplied::instruction()
{
  const static TopOfBookImplied::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
TopOfBookImplied__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("X",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
TopOfBookImplied__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
TopOfBookImplied__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
TopOfBookImplied__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
TopOfBookImplied__MDIncGrp_element__MDIncGrp_length_instruction(
  operator_none,
  presence_mandatory,
  268, // id
  "NoMDEntries", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>()); // initial_value

const static uint32_field_instruction
TopOfBookImplied__MDIncGrp_element__MDUpdateAction_instruction(
  operator_copy,
  presence_mandatory,
  279, // id
  "MDUpdateAction", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
TopOfBookImplied__MDIncGrp_element__MDEntryType_instruction(
  operator_copy,
  presence_mandatory,
  269, // id
  "MDEntryType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
TopOfBookImplied__MDIncGrp_element__MDBookType_instruction(
  operator_constant,
  presence_mandatory,
  1021, // id
  "MDBookType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
TopOfBookImplied__MDIncGrp_element__MDSubBookType_instruction(
  operator_copy,
  presence_mandatory,
  1173, // id
  "MDSubBookType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
TopOfBookImplied__MDIncGrp_element__SecurityID_instruction(
  operator_copy,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
TopOfBookImplied__MDIncGrp_element__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
TopOfBookImplied__MDIncGrp_element__MDEntryPx_instruction(
  operator_delta,
  presence_optional,
  270, // id
  "MDEntryPx", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
TopOfBookImplied__MDIncGrp_element__MDEntrySize_instruction(
  operator_delta,
  presence_optional,
  271, // id
  "MDEntrySize", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
TopOfBookImplied__MDIncGrp_element__MDEntryTime_instruction(
  operator_copy,
  presence_optional,
  273, // id
  "MDEntryTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
TopOfBookImplied__MDIncGrp_element__QuoteCondition_instruction(
  operator_copy,
  presence_optional,
  276, // id
  "QuoteCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* TopOfBookImplied__MDIncGrp_element__subinstructions[] = {
  &TopOfBookImplied__MDIncGrp_element__MDUpdateAction_instruction,
  &TopOfBookImplied__MDIncGrp_element__MDEntryType_instruction,
  &TopOfBookImplied__MDIncGrp_element__MDBookType_instruction,
  &TopOfBookImplied__MDIncGrp_element__MDSubBookType_instruction,
  &TopOfBookImplied__MDIncGrp_element__SecurityID_instruction,
  &TopOfBookImplied__MDIncGrp_element__SecurityIDSource_instruction,
  &TopOfBookImplied__MDIncGrp_element__MDEntryPx_instruction,
  &TopOfBookImplied__MDIncGrp_element__MDEntrySize_instruction,
  &TopOfBookImplied__MDIncGrp_element__MDEntryTime_instruction,
  &TopOfBookImplied__MDIncGrp_element__QuoteCondition_instruction,
};

const static TopOfBookImplied_cref::MDIncGrp_cref::instruction_type
TopOfBookImplied__MDIncGrp_instruction(
  presence_mandatory,
  0, // id
  "MDIncGrp", // name
  "", // ns
  "", // dictionary
  TopOfBookImplied__MDIncGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &TopOfBookImplied__MDIncGrp_element__MDIncGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static field_instruction* TopOfBookImplied__subinstructions[] = {
  &TopOfBookImplied__MsgType_instruction,
  &TopOfBookImplied__MsgSeqNum_instruction,
  &TopOfBookImplied__SenderCompID_instruction,
  &TopOfBookImplied__MarketSegmentID_instruction,
  &TopOfBookImplied__MDIncGrp_instruction,
};

  const static TopOfBookImplied::instruction_type the_instruction(
    513, // id
    "TopOfBookImplied", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    TopOfBookImplied__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const FlexibleInstrumentUpdate::instruction_type*
FlexibleInstrumentUpdate::instruction()
{
  const static FlexibleInstrumentUpdate::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
FlexibleInstrumentUpdate__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("BP",2), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
FlexibleInstrumentUpdate__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
FlexibleInstrumentUpdate__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
FlexibleInstrumentUpdate__SecurityUpdateAction_instruction(
  operator_constant,
  presence_mandatory,
  980, // id
  "SecurityUpdateAction", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("A",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
FlexibleInstrumentUpdate__SecurityID_instruction(
  operator_none,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
FlexibleInstrumentUpdate__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
FlexibleInstrumentUpdate__SecurityDesc_instruction(
  operator_none,
  presence_mandatory,
  107, // id
  "SecurityDesc", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
FlexibleInstrumentUpdate__SecurityType_instruction(
  operator_none,
  presence_mandatory,
  167, // id
  "SecurityType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
FlexibleInstrumentUpdate__ProductComplex_instruction(
  operator_none,
  presence_mandatory,
  1227, // id
  "ProductComplex", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
FlexibleInstrumentUpdate__MaturityDate_instruction(
  operator_none,
  presence_mandatory,
  541, // id
  "MaturityDate", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
FlexibleInstrumentUpdate__StrikePrice_instruction(
  operator_none,
  presence_optional,
  202, // id
  "StrikePrice", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
FlexibleInstrumentUpdate__PutOrCall_instruction(
  operator_none,
  presence_optional,
  201, // id
  "PutOrCall", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
FlexibleInstrumentUpdate__OptAttribute_instruction(
  operator_none,
  presence_optional,
  206, // id
  "OptAttribute", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
FlexibleInstrumentUpdate__ExerciseStyle_instruction(
  operator_none,
  presence_optional,
  1194, // id
  "ExerciseStyle", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
FlexibleInstrumentUpdate__SettlMethod_instruction(
  operator_none,
  presence_mandatory,
  1193, // id
  "SettlMethod", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
FlexibleInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentGrp_length_instruction(
  operator_constant,
  presence_mandatory,
  1310, // id
  "NoMarketSegments", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U)); // initial_value

const static uint32_field_instruction
FlexibleInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* FlexibleInstrumentUpdate__MarketSegmentGrp_element__subinstructions[] = {
  &FlexibleInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentID_instruction,
};

const static FlexibleInstrumentUpdate_cref::MarketSegmentGrp_cref::instruction_type
FlexibleInstrumentUpdate__MarketSegmentGrp_instruction(
  presence_mandatory,
  0, // id
  "MarketSegmentGrp", // name
  "", // ns
  "", // dictionary
  FlexibleInstrumentUpdate__MarketSegmentGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &FlexibleInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static int64_field_instruction
FlexibleInstrumentUpdate__TransactTime_instruction(
  operator_none,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* FlexibleInstrumentUpdate__subinstructions[] = {
  &FlexibleInstrumentUpdate__MsgType_instruction,
  &FlexibleInstrumentUpdate__MsgSeqNum_instruction,
  &FlexibleInstrumentUpdate__SenderCompID_instruction,
  &FlexibleInstrumentUpdate__SecurityUpdateAction_instruction,
  &FlexibleInstrumentUpdate__SecurityID_instruction,
  &FlexibleInstrumentUpdate__SecurityIDSource_instruction,
  &FlexibleInstrumentUpdate__SecurityDesc_instruction,
  &FlexibleInstrumentUpdate__SecurityType_instruction,
  &FlexibleInstrumentUpdate__ProductComplex_instruction,
  &FlexibleInstrumentUpdate__MaturityDate_instruction,
  &FlexibleInstrumentUpdate__StrikePrice_instruction,
  &FlexibleInstrumentUpdate__PutOrCall_instruction,
  &FlexibleInstrumentUpdate__OptAttribute_instruction,
  &FlexibleInstrumentUpdate__ExerciseStyle_instruction,
  &FlexibleInstrumentUpdate__SettlMethod_instruction,
  &FlexibleInstrumentUpdate__MarketSegmentGrp_instruction,
  &FlexibleInstrumentUpdate__TransactTime_instruction,
};

  const static FlexibleInstrumentUpdate::instruction_type the_instruction(
    110, // id
    "FlexibleInstrumentUpdate", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    FlexibleInstrumentUpdate__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const Reset::instruction_type*
Reset::instruction()
{
  const static Reset::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static mfast::instructions_view_t Reset__subinstructions;

  const static Reset::instruction_type the_instruction(
    120, // id
    "Reset", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    Reset__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const template_instruction* MDIFastTemplates_1_1_templates_instructions[] ={
  MDPacketHeader::instruction(),
  ProductStateChange::instruction(),
  MassInstrumentStateChange::instruction(),
  InstrumentStateChange::instruction(),
  DepthIncremental::instruction(),
  ComplexInstrumentUpdate::instruction(),
  QuoteRequest::instruction(),
  CrossRequest::instruction(),
  DepthSnapshot::instruction(),
  IndexStats::instruction(),
  TopOfBookImplied::instruction(),
  FlexibleInstrumentUpdate::instruction(),
  Reset::instruction()};

templates_description::templates_description()
  : mfast::templates_description(
    "", // ns
    "http://www.deutsche-boerse.com/ns/fast/mdnfast", // templateNs
    "", // dictionary
    MDIFastTemplates_1_1_templates_instructions)
{
}

const templates_description* templates_description::instance()
{
  static const templates_description inst;
  return &inst;
}

}
