// MDIFastTemplates_1_1.cpp generated by mFAST from FAST Template. 
// Do not modify this file directly. Any modifications 
// will be lost the next time this file is generated.

#include "MDIFastTemplates_1_1.h"

using namespace mfast;

namespace MDIFastTemplates_1_1
{
const MDPacketHeader::instruction_type*
MDPacketHeader::instruction()
{
  const static MDPacketHeader::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static uint32_field_instruction
MDPacketHeader__SenderCompID_instruction(
  operator_none,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static byte_vector_field_instruction
MDPacketHeader__PacketSeqNum_instruction(
  operator_none,
  presence_mandatory,
  0, // id
  "PacketSeqNum", // name
  "", // ns
  nullptr,  // opContext
  byte_vector_value_storage(), // initial value
  0, // length id
  "", // length name
  "", // length ns
  mfast::instruction_tag(0)); // tag

const static byte_vector_field_instruction
MDPacketHeader__SendingTime_instruction(
  operator_none,
  presence_mandatory,
  0, // id
  "SendingTime", // name
  "", // ns
  nullptr,  // opContext
  byte_vector_value_storage(), // initial value
  0, // length id
  "", // length name
  "", // length ns
  mfast::instruction_tag(0)); // tag

const static field_instruction* MDPacketHeader__subinstructions[] = {
  &MDPacketHeader__SenderCompID_instruction,
  &MDPacketHeader__PacketSeqNum_instruction,
  &MDPacketHeader__SendingTime_instruction,
};

  const static MDPacketHeader::instruction_type the_instruction(
    122, // id
    "MDPacketHeader", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    MDPacketHeader__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const ProductStateChange::instruction_type*
ProductStateChange::instruction()
{
  const static ProductStateChange::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
ProductStateChange__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("h",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__TradingSessionID_instruction(
  operator_default,
  presence_mandatory,
  336, // id
  "TradingSessionID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__TradingSessionSubID_instruction(
  operator_none,
  presence_mandatory,
  625, // id
  "TradingSessionSubID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__TradSesStatus_instruction(
  operator_none,
  presence_mandatory,
  340, // id
  "TradSesStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ProductStateChange__FastMarketIndicator_instruction(
  operator_default,
  presence_mandatory,
  28828, // id
  "FastMarketIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
ProductStateChange__TransactTime_instruction(
  operator_none,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* ProductStateChange__subinstructions[] = {
  &ProductStateChange__MsgType_instruction,
  &ProductStateChange__MsgSeqNum_instruction,
  &ProductStateChange__SenderCompID_instruction,
  &ProductStateChange__MarketSegmentID_instruction,
  &ProductStateChange__TradingSessionID_instruction,
  &ProductStateChange__TradingSessionSubID_instruction,
  &ProductStateChange__TradSesStatus_instruction,
  &ProductStateChange__FastMarketIndicator_instruction,
  &ProductStateChange__TransactTime_instruction,
};

  const static ProductStateChange::instruction_type the_instruction(
    108, // id
    "ProductStateChange", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    ProductStateChange__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const MassInstrumentStateChange::instruction_type*
MassInstrumentStateChange::instruction()
{
  const static MassInstrumentStateChange::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
MassInstrumentStateChange__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("CO",2), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__InstrumentScopeProductComplex_instruction(
  operator_copy,
  presence_mandatory,
  1544, // id
  "InstrumentScopeProductComplex", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecurityMassTradingStatus_instruction(
  operator_copy,
  presence_mandatory,
  1679, // id
  "SecurityMassTradingStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__FastMarketIndicator_instruction(
  operator_default,
  presence_mandatory,
  28828, // id
  "FastMarketIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
MassInstrumentStateChange__TransactTime_instruction(
  operator_delta,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecMassStatGrp_length_instruction(
  operator_default,
  presence_mandatory,
  146, // id
  "NoRelatedSym", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U)); // initial_value

const static int64_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecurityID_instruction(
  operator_none,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecurityStatus_instruction(
  operator_default,
  presence_mandatory,
  965, // id
  "SecurityStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
MassInstrumentStateChange__SecMassStatGrp_element__SecurityTradingStatus_instruction(
  operator_copy,
  presence_mandatory,
  326, // id
  "SecurityTradingStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* MassInstrumentStateChange__SecMassStatGrp_element__subinstructions[] = {
  &MassInstrumentStateChange__SecMassStatGrp_element__SecurityID_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_element__SecurityIDSource_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_element__SecurityStatus_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_element__SecurityTradingStatus_instruction,
};

const static MassInstrumentStateChange_cref::SecMassStatGrp_cref::instruction_type
MassInstrumentStateChange__SecMassStatGrp_instruction(
  presence_mandatory,
  0, // id
  "SecMassStatGrp", // name
  "", // ns
  "", // dictionary
  MassInstrumentStateChange__SecMassStatGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &MassInstrumentStateChange__SecMassStatGrp_element__SecMassStatGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static field_instruction* MassInstrumentStateChange__subinstructions[] = {
  &MassInstrumentStateChange__MsgType_instruction,
  &MassInstrumentStateChange__MsgSeqNum_instruction,
  &MassInstrumentStateChange__SenderCompID_instruction,
  &MassInstrumentStateChange__MarketSegmentID_instruction,
  &MassInstrumentStateChange__InstrumentScopeProductComplex_instruction,
  &MassInstrumentStateChange__SecurityMassTradingStatus_instruction,
  &MassInstrumentStateChange__FastMarketIndicator_instruction,
  &MassInstrumentStateChange__TransactTime_instruction,
  &MassInstrumentStateChange__SecMassStatGrp_instruction,
};

  const static MassInstrumentStateChange::instruction_type the_instruction(
    104, // id
    "MassInstrumentStateChange", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    MassInstrumentStateChange__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const InstrumentStateChange::instruction_type*
InstrumentStateChange::instruction()
{
  const static InstrumentStateChange::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
InstrumentStateChange__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("f",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
InstrumentStateChange__SecurityID_instruction(
  operator_none,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
InstrumentStateChange__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__SecurityStatus_instruction(
  operator_default,
  presence_mandatory,
  965, // id
  "SecurityStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__SecurityTradingStatus_instruction(
  operator_copy,
  presence_mandatory,
  326, // id
  "SecurityTradingStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
InstrumentStateChange__FastMarketIndicator_instruction(
  operator_default,
  presence_mandatory,
  28828, // id
  "FastMarketIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
InstrumentStateChange__TransactTime_instruction(
  operator_delta,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* InstrumentStateChange__subinstructions[] = {
  &InstrumentStateChange__MsgType_instruction,
  &InstrumentStateChange__MsgSeqNum_instruction,
  &InstrumentStateChange__SenderCompID_instruction,
  &InstrumentStateChange__MarketSegmentID_instruction,
  &InstrumentStateChange__SecurityID_instruction,
  &InstrumentStateChange__SecurityIDSource_instruction,
  &InstrumentStateChange__SecurityStatus_instruction,
  &InstrumentStateChange__SecurityTradingStatus_instruction,
  &InstrumentStateChange__FastMarketIndicator_instruction,
  &InstrumentStateChange__TransactTime_instruction,
};

  const static InstrumentStateChange::instruction_type the_instruction(
    103, // id
    "InstrumentStateChange", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    InstrumentStateChange__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const DepthIncremental::instruction_type*
DepthIncremental::instruction()
{
  const static DepthIncremental::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
DepthIncremental__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("X",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
DepthIncremental__MDIncGrp_element__MDIncGrp_length_instruction(
  operator_none,
  presence_mandatory,
  268, // id
  "NoMDEntries", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>()); // initial_value

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__MDUpdateAction_instruction(
  operator_copy,
  presence_mandatory,
  279, // id
  "MDUpdateAction", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__MDEntryType_instruction(
  operator_copy,
  presence_mandatory,
  269, // id
  "MDEntryType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthIncremental__MDIncGrp_element__SecurityID_instruction(
  operator_copy,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
DepthIncremental__MDIncGrp_element__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__MDEntryPx_instruction(
  operator_delta,
  presence_optional,
  270, // id
  "MDEntryPx", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__Yield_instruction(
  operator_delta,
  presence_optional,
  236, // id
  "Yield", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__PutYield_instruction(
  operator_delta,
  presence_optional,
  30630, // id
  "PutYield", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthIncremental__MDIncGrp_element__CallYield_instruction(
  operator_delta,
  presence_optional,
  30631, // id
  "CallYield", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__MDEntrySize_instruction(
  operator_delta,
  presence_optional,
  271, // id
  "MDEntrySize", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__NumberOfOrders_instruction(
  operator_delta,
  presence_optional,
  346, // id
  "NumberOfOrders", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__MDPriceLevel_instruction(
  operator_none,
  presence_optional,
  1023, // id
  "MDPriceLevel", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint64_field_instruction
DepthIncremental__MDIncGrp_element__BidSize_instruction(
  operator_copy,
  presence_optional,
  134, // id
  "BidSize", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint64_field_instruction
DepthIncremental__MDIncGrp_element__OfferSize_instruction(
  operator_copy,
  presence_optional,
  135, // id
  "OfferSize", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthIncremental__MDIncGrp_element__MDEntryTime_instruction(
  operator_copy,
  presence_optional,
  273, // id
  "MDEntryTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__TrdType_instruction(
  operator_none,
  presence_optional,
  828, // id
  "TrdType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint64_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__TradeVolume_instruction(
  operator_none,
  presence_optional,
  1020, // id
  "TradeVolume", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint64_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__TradeCondition_instruction(
  operator_default,
  presence_optional,
  277, // id
  "TradeCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint64_t>(1ULL), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__MDGapIndicator_instruction(
  operator_constant,
  presence_optional,
  28819, // id
  "MDGapIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__AggressorTimestamp_instruction(
  operator_none,
  presence_optional,
  28820, // id
  "AggressorTimestamp", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__AggressorSide_instruction(
  operator_none,
  presence_optional,
  28731, // id
  "AggressorSide", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__NumberOfBuyOrders_instruction(
  operator_none,
  presence_optional,
  28821, // id
  "NumberOfBuyOrders", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__NumberOfSellOrders_instruction(
  operator_none,
  presence_optional,
  28822, // id
  "NumberOfSellOrders", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthIncremental__MDIncGrp_element__TradeEntryGrp__MDEntryID_instruction(
  operator_delta,
  presence_optional,
  278, // id
  "MDEntryID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* DepthIncremental__MDIncGrp_element__TradeEntryGrp__subinstructions[] = {
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__TrdType_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__TradeVolume_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__TradeCondition_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__MDGapIndicator_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__AggressorTimestamp_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__AggressorSide_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__NumberOfBuyOrders_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__NumberOfSellOrders_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp__MDEntryID_instruction,
};

const static DepthIncremental_cref::MDIncGrp_element_cref::TradeEntryGrp_cref::instruction_type
DepthIncremental__MDIncGrp_element__TradeEntryGrp_instruction(
  presence_optional,
  0, // id
  "TradeEntryGrp", // name
  "", // ns
  "", // dictionary
  DepthIncremental__MDIncGrp_element__TradeEntryGrp__subinstructions,
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag

const static field_instruction* DepthIncremental__MDIncGrp_element__subinstructions[] = {
  &DepthIncremental__MDIncGrp_element__MDUpdateAction_instruction,
  &DepthIncremental__MDIncGrp_element__MDEntryType_instruction,
  &DepthIncremental__MDIncGrp_element__SecurityID_instruction,
  &DepthIncremental__MDIncGrp_element__SecurityIDSource_instruction,
  &DepthIncremental__MDIncGrp_element__MDEntryPx_instruction,
  &DepthIncremental__MDIncGrp_element__Yield_instruction,
  &DepthIncremental__MDIncGrp_element__PutYield_instruction,
  &DepthIncremental__MDIncGrp_element__CallYield_instruction,
  &DepthIncremental__MDIncGrp_element__MDEntrySize_instruction,
  &DepthIncremental__MDIncGrp_element__NumberOfOrders_instruction,
  &DepthIncremental__MDIncGrp_element__MDPriceLevel_instruction,
  &DepthIncremental__MDIncGrp_element__BidSize_instruction,
  &DepthIncremental__MDIncGrp_element__OfferSize_instruction,
  &DepthIncremental__MDIncGrp_element__MDEntryTime_instruction,
  &DepthIncremental__MDIncGrp_element__TradeEntryGrp_instruction,
};

const static DepthIncremental_cref::MDIncGrp_cref::instruction_type
DepthIncremental__MDIncGrp_instruction(
  presence_mandatory,
  0, // id
  "MDIncGrp", // name
  "", // ns
  "", // dictionary
  DepthIncremental__MDIncGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &DepthIncremental__MDIncGrp_element__MDIncGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static field_instruction* DepthIncremental__subinstructions[] = {
  &DepthIncremental__MsgType_instruction,
  &DepthIncremental__MsgSeqNum_instruction,
  &DepthIncremental__SenderCompID_instruction,
  &DepthIncremental__MarketSegmentID_instruction,
  &DepthIncremental__MDIncGrp_instruction,
};

  const static DepthIncremental::instruction_type the_instruction(
    102, // id
    "DepthIncremental", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    DepthIncremental__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const ComplexInstrumentUpdate::instruction_type*
ComplexInstrumentUpdate::instruction()
{
  const static ComplexInstrumentUpdate::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
ComplexInstrumentUpdate__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("BP",2), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
ComplexInstrumentUpdate__SecurityUpdateAction_instruction(
  operator_constant,
  presence_mandatory,
  980, // id
  "SecurityUpdateAction", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("A",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
ComplexInstrumentUpdate__SecurityID_instruction(
  operator_none,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
ComplexInstrumentUpdate__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
ComplexInstrumentUpdate__SecurityDesc_instruction(
  operator_none,
  presence_mandatory,
  107, // id
  "SecurityDesc", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__SecurityType_instruction(
  operator_constant,
  presence_mandatory,
  167, // id
  "SecurityType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(2U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__SecuritySubType_instruction(
  operator_none,
  presence_optional,
  762, // id
  "SecuritySubType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__ProductComplex_instruction(
  operator_copy,
  presence_mandatory,
  1227, // id
  "ProductComplex", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__InstrmtLegGrp_length_instruction(
  operator_none,
  presence_mandatory,
  555, // id
  "NoLegs", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>()); // initial_value

const static int64_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSecurityID_instruction(
  operator_none,
  presence_mandatory,
  602, // id
  "LegSecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  603, // id
  "LegSecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegRatioQty_instruction(
  operator_none,
  presence_mandatory,
  623, // id
  "LegRatioQty", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSide_instruction(
  operator_copy,
  presence_mandatory,
  624, // id
  "LegSide", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
ComplexInstrumentUpdate__InstrmtLegGrp_element__LegPrice_instruction(
  operator_none,
  presence_optional,
  566, // id
  "LegPrice", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* ComplexInstrumentUpdate__InstrmtLegGrp_element__subinstructions[] = {
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSecurityID_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSecurityIDSource_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegRatioQty_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegSide_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__LegPrice_instruction,
};

const static ComplexInstrumentUpdate_cref::InstrmtLegGrp_cref::instruction_type
ComplexInstrumentUpdate__InstrmtLegGrp_instruction(
  presence_mandatory,
  0, // id
  "InstrmtLegGrp", // name
  "", // ns
  "", // dictionary
  ComplexInstrumentUpdate__InstrmtLegGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &ComplexInstrumentUpdate__InstrmtLegGrp_element__InstrmtLegGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

static uint32_field_instruction
ComplexInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentGrp_length_instruction(
  operator_constant,
  presence_mandatory,
  1310, // id
  "NoMarketSegments", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U)); // initial_value

const static uint32_field_instruction
ComplexInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
ComplexInstrumentUpdate__MarketSegmentGrp_element__ImpliedMarketIndicator_instruction(
  operator_none,
  presence_mandatory,
  1144, // id
  "ImpliedMarketIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* ComplexInstrumentUpdate__MarketSegmentGrp_element__subinstructions[] = {
  &ComplexInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentID_instruction,
  &ComplexInstrumentUpdate__MarketSegmentGrp_element__ImpliedMarketIndicator_instruction,
};

const static ComplexInstrumentUpdate_cref::MarketSegmentGrp_cref::instruction_type
ComplexInstrumentUpdate__MarketSegmentGrp_instruction(
  presence_mandatory,
  0, // id
  "MarketSegmentGrp", // name
  "", // ns
  "", // dictionary
  ComplexInstrumentUpdate__MarketSegmentGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &ComplexInstrumentUpdate__MarketSegmentGrp_element__MarketSegmentGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static int64_field_instruction
ComplexInstrumentUpdate__TransactTime_instruction(
  operator_none,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* ComplexInstrumentUpdate__subinstructions[] = {
  &ComplexInstrumentUpdate__MsgType_instruction,
  &ComplexInstrumentUpdate__MsgSeqNum_instruction,
  &ComplexInstrumentUpdate__SenderCompID_instruction,
  &ComplexInstrumentUpdate__SecurityUpdateAction_instruction,
  &ComplexInstrumentUpdate__SecurityID_instruction,
  &ComplexInstrumentUpdate__SecurityIDSource_instruction,
  &ComplexInstrumentUpdate__SecurityDesc_instruction,
  &ComplexInstrumentUpdate__SecurityType_instruction,
  &ComplexInstrumentUpdate__SecuritySubType_instruction,
  &ComplexInstrumentUpdate__ProductComplex_instruction,
  &ComplexInstrumentUpdate__InstrmtLegGrp_instruction,
  &ComplexInstrumentUpdate__MarketSegmentGrp_instruction,
  &ComplexInstrumentUpdate__TransactTime_instruction,
};

  const static ComplexInstrumentUpdate::instruction_type the_instruction(
    105, // id
    "ComplexInstrumentUpdate", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    ComplexInstrumentUpdate__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const QuoteRequest::instruction_type*
QuoteRequest::instruction()
{
  const static QuoteRequest::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
QuoteRequest__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("R",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
QuoteRequest__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
QuoteRequest__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
QuoteRequest__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
QuoteRequest__QuotReqGrp_element__QuotReqGrp_length_instruction(
  operator_constant,
  presence_mandatory,
  146, // id
  "NoRelatedSym", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U)); // initial_value

const static int64_field_instruction
QuoteRequest__QuotReqGrp_element__SecurityID_instruction(
  operator_copy,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
QuoteRequest__QuotReqGrp_element__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
QuoteRequest__QuotReqGrp_element__Side_instruction(
  operator_copy,
  presence_optional,
  54, // id
  "Side", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
QuoteRequest__QuotReqGrp_element__OrderQty_instruction(
  operator_delta,
  presence_optional,
  38, // id
  "OrderQty", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
QuoteRequest__QuotReqGrp_element__TransactTime_instruction(
  operator_copy,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* QuoteRequest__QuotReqGrp_element__subinstructions[] = {
  &QuoteRequest__QuotReqGrp_element__SecurityID_instruction,
  &QuoteRequest__QuotReqGrp_element__SecurityIDSource_instruction,
  &QuoteRequest__QuotReqGrp_element__Side_instruction,
  &QuoteRequest__QuotReqGrp_element__OrderQty_instruction,
  &QuoteRequest__QuotReqGrp_element__TransactTime_instruction,
};

const static QuoteRequest_cref::QuotReqGrp_cref::instruction_type
QuoteRequest__QuotReqGrp_instruction(
  presence_mandatory,
  0, // id
  "QuotReqGrp", // name
  "", // ns
  "", // dictionary
  QuoteRequest__QuotReqGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &QuoteRequest__QuotReqGrp_element__QuotReqGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static field_instruction* QuoteRequest__subinstructions[] = {
  &QuoteRequest__MsgType_instruction,
  &QuoteRequest__MsgSeqNum_instruction,
  &QuoteRequest__SenderCompID_instruction,
  &QuoteRequest__MarketSegmentID_instruction,
  &QuoteRequest__QuotReqGrp_instruction,
};

  const static QuoteRequest::instruction_type the_instruction(
    106, // id
    "QuoteRequest", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    QuoteRequest__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const CrossRequest::instruction_type*
CrossRequest::instruction()
{
  const static CrossRequest::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
CrossRequest__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("U16",3), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
CrossRequest__MsgSeqNum_instruction(
  operator_increment,
  presence_mandatory,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
CrossRequest__SenderCompID_instruction(
  operator_none,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
CrossRequest__MarketSegmentID_instruction(
  operator_none,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
CrossRequest__SecurityID_instruction(
  operator_none,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
CrossRequest__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
CrossRequest__OrderQty_instruction(
  operator_none,
  presence_mandatory,
  38, // id
  "OrderQty", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
CrossRequest__TransactTime_instruction(
  operator_none,
  presence_mandatory,
  60, // id
  "TransactTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* CrossRequest__subinstructions[] = {
  &CrossRequest__MsgType_instruction,
  &CrossRequest__MsgSeqNum_instruction,
  &CrossRequest__SenderCompID_instruction,
  &CrossRequest__MarketSegmentID_instruction,
  &CrossRequest__SecurityID_instruction,
  &CrossRequest__SecurityIDSource_instruction,
  &CrossRequest__OrderQty_instruction,
  &CrossRequest__TransactTime_instruction,
};

  const static CrossRequest::instruction_type the_instruction(
    107, // id
    "CrossRequest", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    CrossRequest__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const DepthSnapshot::instruction_type*
DepthSnapshot::instruction()
{
  const static DepthSnapshot::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
DepthSnapshot__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("W",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MsgSeqNum_instruction(
  operator_increment,
  presence_optional,
  34, // id
  "MsgSeqNum", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__SenderCompID_instruction(
  operator_copy,
  presence_mandatory,
  49, // id
  "SenderCompID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__LastMsgSeqNumProcessed_instruction(
  operator_increment,
  presence_optional,
  369, // id
  "LastMsgSeqNumProcessed", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__RefreshIndicator_instruction(
  operator_copy,
  presence_optional,
  1187, // id
  "RefreshIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MarketSegmentID_instruction(
  operator_copy,
  presence_mandatory,
  1300, // id
  "MarketSegmentID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthSnapshot__SecurityID_instruction(
  operator_delta,
  presence_mandatory,
  48, // id
  "SecurityID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static ascii_field_instruction
DepthSnapshot__SecurityIDSource_instruction(
  operator_constant,
  presence_mandatory,
  22, // id
  "SecurityIDSource", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("M",1), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__ProductComplex_instruction(
  operator_copy,
  presence_mandatory,
  1227, // id
  "ProductComplex", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__SecurityStatus_instruction(
  operator_default,
  presence_mandatory,
  965, // id
  "SecurityStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint64_field_instruction
DepthSnapshot__BidSize_instruction(
  operator_copy,
  presence_mandatory,
  134, // id
  "BidSize", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint64_field_instruction
DepthSnapshot__OfferSize_instruction(
  operator_copy,
  presence_mandatory,
  135, // id
  "OfferSize", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthSnapshot__LastUpdateTime_instruction(
  operator_delta,
  presence_mandatory,
  779, // id
  "LastUpdateTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MDSshGrp_length_instruction(
  operator_default,
  presence_mandatory,
  268, // id
  "NoMDEntries", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(1U)); // initial_value

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MDEntryType_instruction(
  operator_copy,
  presence_mandatory,
  269, // id
  "MDEntryType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__TrdType_instruction(
  operator_none,
  presence_optional,
  828, // id
  "TrdType", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__TradingSessionID_instruction(
  operator_default,
  presence_optional,
  336, // id
  "TradingSessionID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__TradingSessionSubID_instruction(
  operator_none,
  presence_optional,
  625, // id
  "TradingSessionSubID", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__FastMarketIndicator_instruction(
  operator_default,
  presence_optional,
  28828, // id
  "FastMarketIndicator", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(0U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__SecurityTradingStatus_instruction(
  operator_none,
  presence_optional,
  326, // id
  "SecurityTradingStatus", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint64_field_instruction
DepthSnapshot__MDSshGrp_element__TradeCondition_instruction(
  operator_none,
  presence_optional,
  277, // id
  "TradeCondition", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__MDSshGrp_element__MDEntryPx_instruction(
  operator_delta,
  presence_optional,
  270, // id
  "MDEntryPx", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__MDSshGrp_element__Yield_instruction(
  operator_delta,
  presence_optional,
  236, // id
  "Yield", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__MDSshGrp_element__PutYield_instruction(
  operator_delta,
  presence_optional,
  30630, // id
  "PutYield", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__MDSshGrp_element__CallYield_instruction(
  operator_delta,
  presence_optional,
  30631, // id
  "CallYield", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MDEntrySize_instruction(
  operator_delta,
  presence_optional,
  271, // id
  "MDEntrySize", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__NumberOfOrders_instruction(
  operator_delta,
  presence_optional,
  346, // id
  "NumberOfOrders", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__MDPriceLevel_instruction(
  operator_increment,
  presence_optional,
  1023, // id
  "MDPriceLevel", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static int64_field_instruction
DepthSnapshot__MDSshGrp_element__MDEntryTime_instruction(
  operator_copy,
  presence_optional,
  273, // id
  "MDEntryTime", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<int64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint64_field_instruction
DepthSnapshot__MDSshGrp_element__TradeVolume_instruction(
  operator_none,
  presence_optional,
  1020, // id
  "TradeVolume", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint64_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static decimal_field_instruction
DepthSnapshot__MDSshGrp_element__GrossTradeAmt_instruction(
  operator_none,
  presence_optional,
  381, // id
  "GrossTradeAmt", // name
  "", // ns
  nullptr,  // opContext
  decimal_value_storage(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
DepthSnapshot__MDSshGrp_element__NoTrades_instruction(
  operator_none,
  presence_optional,
  897, // id
  "NoTrades", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* DepthSnapshot__MDSshGrp_element__subinstructions[] = {
  &DepthSnapshot__MDSshGrp_element__MDEntryType_instruction,
  &DepthSnapshot__MDSshGrp_element__TrdType_instruction,
  &DepthSnapshot__MDSshGrp_element__TradingSessionID_instruction,
  &DepthSnapshot__MDSshGrp_element__TradingSessionSubID_instruction,
  &DepthSnapshot__MDSshGrp_element__FastMarketIndicator_instruction,
  &DepthSnapshot__MDSshGrp_element__SecurityTradingStatus_instruction,
  &DepthSnapshot__MDSshGrp_element__TradeCondition_instruction,
  &DepthSnapshot__MDSshGrp_element__MDEntryPx_instruction,
  &DepthSnapshot__MDSshGrp_element__Yield_instruction,
  &DepthSnapshot__MDSshGrp_element__PutYield_instruction,
  &DepthSnapshot__MDSshGrp_element__CallYield_instruction,
  &DepthSnapshot__MDSshGrp_element__MDEntrySize_instruction,
  &DepthSnapshot__MDSshGrp_element__NumberOfOrders_instruction,
  &DepthSnapshot__MDSshGrp_element__MDPriceLevel_instruction,
  &DepthSnapshot__MDSshGrp_element__MDEntryTime_instruction,
  &DepthSnapshot__MDSshGrp_element__TradeVolume_instruction,
  &DepthSnapshot__MDSshGrp_element__GrossTradeAmt_instruction,
  &DepthSnapshot__MDSshGrp_element__NoTrades_instruction,
};

const static DepthSnapshot_cref::MDSshGrp_cref::instruction_type
DepthSnapshot__MDSshGrp_instruction(
  presence_mandatory,
  0, // id
  "MDSshGrp", // name
  "", // ns
  "", // dictionary
  DepthSnapshot__MDSshGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &DepthSnapshot__MDSshGrp_element__MDSshGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static field_instruction* DepthSnapshot__subinstructions[] = {
  &DepthSnapshot__MsgType_instruction,
  &DepthSnapshot__MsgSeqNum_instruction,
  &DepthSnapshot__SenderCompID_instruction,
  &DepthSnapshot__LastMsgSeqNumProcessed_instruction,
  &DepthSnapshot__RefreshIndicator_instruction,
  &DepthSnapshot__MarketSegmentID_instruction,
  &DepthSnapshot__SecurityID_instruction,
  &DepthSnapshot__SecurityIDSource_instruction,
  &DepthSnapshot__ProductComplex_instruction,
  &DepthSnapshot__SecurityStatus_instruction,
  &DepthSnapshot__BidSize_instruction,
  &DepthSnapshot__OfferSize_instruction,
  &DepthSnapshot__LastUpdateTime_instruction,
  &DepthSnapshot__MDSshGrp_instruction,
};

  const static DepthSnapshot::instruction_type the_instruction(
    101, // id
    "DepthSnapshot", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    DepthSnapshot__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const IndexChange::instruction_type*
IndexChange::instruction()
{
  const static IndexChange::instruction_type* ptr_instruction;
  if (ptr_instruction) return ptr_instruction;
const static ascii_field_instruction
IndexChange__MsgType_instruction(
  operator_constant,
  presence_mandatory,
  35, // id
  "MsgType", // name
  "", // ns
  nullptr,  // opContext
  string_value_storage("I",1), // initial_value
  mfast::instruction_tag(0)); // tag

static uint32_field_instruction
IndexChange__IndexChgGrp_element__IndexChgGrp_length_instruction(
  operator_none,
  presence_mandatory,
  30621, // id
  "NoOfEntries", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>()); // initial_value

const static uint32_field_instruction
IndexChange__IndexChgGrp_element__Divisor_instruction(
  operator_default,
  presence_optional,
  30622, // id
  "Divisor", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(100U), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexChange__IndexChgGrp_element__IndexCode_instruction(
  operator_none,
  presence_mandatory,
  30623, // id
  "IndexCode", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexChange__IndexChgGrp_element__IndexHigh_instruction(
  operator_none,
  presence_mandatory,
  30624, // id
  "IndexHigh", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexChange__IndexChgGrp_element__IndexLow_instruction(
  operator_none,
  presence_mandatory,
  30625, // id
  "IndexLow", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexChange__IndexChgGrp_element__IndexOpen_instruction(
  operator_none,
  presence_mandatory,
  30626, // id
  "IndexOpen", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexChange__IndexChgGrp_element__PrevIndexClose_instruction(
  operator_none,
  presence_mandatory,
  30627, // id
  "PrevIndexClose", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexChange__IndexChgGrp_element__IndexClose_instruction(
  operator_none,
  presence_mandatory,
  30628, // id
  "IndexClose", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static uint32_field_instruction
IndexChange__IndexChgGrp_element__IndexValue_instruction(
  operator_none,
  presence_mandatory,
  30629, // id
  "IndexValue", // name
  "", // ns
  nullptr,  // opContext
  int_value_storage<uint32_t>(), // initial_value
  mfast::instruction_tag(0)); // tag

const static field_instruction* IndexChange__IndexChgGrp_element__subinstructions[] = {
  &IndexChange__IndexChgGrp_element__Divisor_instruction,
  &IndexChange__IndexChgGrp_element__IndexCode_instruction,
  &IndexChange__IndexChgGrp_element__IndexHigh_instruction,
  &IndexChange__IndexChgGrp_element__IndexLow_instruction,
  &IndexChange__IndexChgGrp_element__IndexOpen_instruction,
  &IndexChange__IndexChgGrp_element__PrevIndexClose_instruction,
  &IndexChange__IndexChgGrp_element__IndexClose_instruction,
  &IndexChange__IndexChgGrp_element__IndexValue_instruction,
};

const static IndexChange_cref::IndexChgGrp_cref::instruction_type
IndexChange__IndexChgGrp_instruction(
  presence_mandatory,
  0, // id
  "IndexChgGrp", // name
  "", // ns
  "", // dictionary
  IndexChange__IndexChgGrp_element__subinstructions,
  nullptr, // element_instruction
  nullptr, // ref_instruction
  &IndexChange__IndexChgGrp_element__IndexChgGrp_length_instruction, // length
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); //tag 

const static field_instruction* IndexChange__subinstructions[] = {
  &IndexChange__MsgType_instruction,
  &IndexChange__IndexChgGrp_instruction,
};

  const static IndexChange::instruction_type the_instruction(
    51, // id
    "IndexChange", // name
    "", // ns
    "", // templateNs
    "", // dictionary
    IndexChange__subinstructions,
    0, // reset
  "", // typeRef name 
  "", // typeRef ns 
  "", // cpp_ns
  mfast::instruction_tag(0)); // tag 

  ptr_instruction = &the_instruction;
  return ptr_instruction;
}

const template_instruction* MDIFastTemplates_1_1_templates_instructions[] ={
  MDPacketHeader::instruction(),
  ProductStateChange::instruction(),
  MassInstrumentStateChange::instruction(),
  InstrumentStateChange::instruction(),
  DepthIncremental::instruction(),
  ComplexInstrumentUpdate::instruction(),
  QuoteRequest::instruction(),
  CrossRequest::instruction(),
  DepthSnapshot::instruction(),
  IndexChange::instruction()};

templates_description::templates_description()
  : mfast::templates_description(
    "", // ns
    "http://www.deutsche-boerse.com/ns/fast/mdnfast", // templateNs
    "", // dictionary
    MDIFastTemplates_1_1_templates_instructions)
{
}

const templates_description* templates_description::instance()
{
  static const templates_description inst;
  return &inst;
}

}
