#ifndef FIN_EXCH_API_NSE_TRANSACT_CODES
#define FIN_EXCH_API_NSE_TRANSACT_CODES

namespace FIN {
			enum TransCode
			{
				TrancCode_INVALID,
				TrancCode_TIMESTAMP_LOCAL = 1,

				TransCode_SYSTEM_INFORMATION_IN = 1600,
				TransCode_SYSTEM_INFORMATION_OUT = 1601,
				TransCode_ORDER_MOD_IN = 2040,
				TransCode_ORDER_MOD_REJECT = 2042,
				TransCode_ORDER_CANCEL_IN = 2070,
				TransCode_ORDER_CANCEL_REJECT = 2072,
				TransCode_ORDER_CONFIRMATION = 2073,
				TransCode_ORDER_MOD_CONFIRMATION = 2074,
				TransCode_ORDER_CANCEL_CONFIRMATION = 2075,
				TransCode_CANCEL_NEG_ORDER = 2076,
				TransCode_PRICE_MOD_IN = 2013,
				TransCode_SP_BOARD_LOT_IN = 2100,
				TransCode_TRADE_CONFIRMATION = 2222,
				TransCode_TRADE_ERROR = 2223,
				TransCode_ORDER_ERROR = 2231,
				TransCode_TRADE_CANCEL_CONFIRM = 2282,
				TransCode_TRADE_CANCEL_REJECT = 2286,
				TransCode_TRADE_MODIFY_CONFIRM = 2287,
				TransCode_TRADE_MODIFY_REJECT = 2288,
				TransCode_SIGN_ON_REQUEST_IN = 2300,
				TransCode_SIGN_ON_REQUEST_OUT = 2301,
				TransCode_SIGN_OFF_REQUEST_OUT = 2321,
				TransCode_GIVEUP_APPROVED_IN = 4500,
				TransCode_GIVEUP_APPROVED_OUT = 4501,
				TransCode_GIVEUP_APP_CONFIRM = 4502,
				TransCode_GIVEUP_APP_CONFIRM_TM = 4506,
				TransCode_GIVEUP_REJECTED_IN = 4503,
				TransCode_GIVEUP_REJECTED_OUT = 4504,
				TransCode_GIVEUP_REJ_CONFIRM = 4505,
				TransCode_GIVEUP_REJ_CONFIRM_TM = 4507,
				TransCode_GIVEUP_APPROVE_ALL = 4513,
				TransCode_DOWNLOAD_REQUEST = 7000,
				TransCode_TRADE_CONFIRMATION_TR = 20222,
				TransCode_HEARTBEAT = 23506,

				TransCode_DROP_COPY_DOWNLOAD_REQUEST = 8000,
				
				

			};
}

#endif
